CodeBuildProject:
  Type: AWS::CodeBuild::Project
  Properties:
    Artifacts:
      Type: CODEPIPELINE
    Source:
      Type: CODEPIPELINE
      BuildSpec: |
        version: 0.2
        phases:
          install:
            runtime-versions:
              docker: 18
            commands:
              - echo "Checking network connectivity"
              - ping -c 4 google.com
              - echo "Updating package lists"
              - sudo apt-get clean
              - sudo apt-get -y update || (echo "Retrying update" && sudo apt-get -y update)
              - echo "Installing jq"
              - sudo apt-get -y install jq

    Environment:
      ComputeType: BUILD_GENERAL1_SMALL
      Type: LINUX_CONTAINER
      Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
      PrivilegedMode: True
      EnvironmentVariables:
        - Name: AWS_DEFAULT_REGION
          Value: !Ref AWS::Region
        - Name: REPOSITORY_URI
          Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrDockerRepository}
    Name: !Ref AWS::StackName
    ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/AirflowCodeBuildServiceRole
